#!/bin/bash

pip3 install --upgrade pip
pip3 install TA-lib
pip3 install shadowsocks
pip3 install scikit-learn
pip3 install statsmodels
pip3 install pymysql
pip3 install pyecharts
pip3 install tushare
pip3 install requests-html
pip3 install scipy
pip3 install python-dateutil
pip3 install tornado
pip3 install wxpy
pip3 install cryptography
pip3 install talib
pip3 install pymongo
pip3 install redis
pip3 install pycryptodome
pip3 install jieba
pip3 install nltk

